name = "sub-worker"
main = "_worker.js"
compatibility_date = "2025-07-23"
keep_vars = true

#[[kv_namespaces]]
#binding = "KV"			#KV绑定名默认不可修改

#id = "5bded46428ab4cf5ad994793bbc5c809"					#KV据库id
